name:                automata
version:             0.1.0.0
github:              "ubeF/automata"
license:             BSD3
author:              "Felix Burkard"
copyright:           "2023 Felix Burkard"

extra-source-files:
- README.md
- CHANGELOG.md

description:         Please see the README on GitHub at <https://github.com/ubeF/automata#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- hspec
- QuickCheck

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  exposed-modules:
    - Regular
    - Regular.NFA
    - Regular.NFA.Operators
    - Regular.DFA
    - Regular.Minimal
    - Tokenizer
    - Tokenizer.DFA
    - ContextFree.PDA
tests:
  automata-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - automata
    - hspec
